### ISSUE TITLE
JSBin script err, Chrome 43

### ISSUE THREAD

**Issue by winkler1** [azproduction/html-tui#3]
Hi-
 Guess the JSBin is the live example? It's giving an error in Chrome 43-
![image](https://cloud.githubusercontent.com/assets/883896/8571294/ca272f2a-2553-11e5-90f3-c722122e99d7.png)

**Comment by azproduction** [comment]
Thanks for reporting!

Did not expect issues from rawgit.com. Fixed, please try again http://jsbin.com/yocupi/1/edit?html,output
